export const DUMMY_MEALS = [
    {
      id: 'm1',
      name: 'Sushi',
      category: 'lunch',
      description: 'Finest fish and veggies',
      price: 22.99,
    },
    {
      id: 'm2',
      name: 'Schnitzel',
      category: 'lunch',
      description: 'A german specialty!',
      price: 16.5,
    },
    {
      id: 'm3',
      name: 'Barbecue Burger',
      category: 'lunch',
      description: 'American, raw, meaty',
      price: 12.99,
    },
    {
      id: 'm4',
      name: 'Green Bowl',
      category: 'lunch',
      description: 'Healthy...and green...',
      price: 18.99,
    },
    {
        id: 1,
        name: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.99,
        img: './images/item-1.jpeg',
        description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        quantity:1,
      },
      {
        id: 2,
        name: 'diner double',
        category: 'lunch',
        price: 13.99,
        img: './images/item-2.jpeg',
        description: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
        quantity:1,
      },
      {
        id: 3,
        name: 'godzilla milkshake',
        category: 'shakes',
        price: 6.99,
        img: './images/item-3.jpeg',
        description: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
        quantity:1,
      },
      {
        id: 4,
        name: 'country delight',
        category: 'breakfast',
        price: 20.99,
        img: './images/item-4.jpeg',
        description: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
        quantity:1,
      },
      {
        id: 5,
        name: 'egg attack',
        category: 'lunch',
        price: 22.99,
        img: './images/item-5.jpeg',
        description: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
        quantity:1,
      },
      {
        id: 6,
        name: 'oreo dream',
        category: 'shakes',
        price: 18.99,
        img: './images/item-6.jpeg',
        description: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
        quantity:1,
      },
      {
        id: 7,
        name: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: './images/item-7.jpeg',
        description: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
        quantity:1,
      },
      {
        id: 8,
        name: 'american classic',
        category: 'lunch',
        price: 12.99,
        img: './images/item-8.jpeg',
        description: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
        quantity:1,
      },
      
  ];
